language: clojure
jdk: oraclejdk8

env:
  global:
    - MY_VERSION: $(lein project-version 2> /dev/null)
    - MY_TAG: $(git describe --tags 2> /dev/null)

branches:
  only:
  - master
  - devel
  - "/^feature\\/.+$/"
  - "/^release\\/.+$/"
  - "/^hotfix\\/.+$/"
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"

script:
  - |
    lein test && echo "Done";
    echo "branch: $TRAVIS_BRANCH, version: $MY_VERSION,event: $TRAVIS_EVENT_TYPE, travis-tag: $TRAVIS_TAG, my-tag: $MY_TAG"

# Snapshot: happens only on push to devel (and not on PR, so safe to leave PR-build on).
#           Check on version ensures nothing bad happens if merging from release to devel
#           and forgetting to change version to -SNAPSHOT.
#
# Release: here there's an inconsistency between Git CLI and GitHub UI.

# - Setting a  tag using  "Releases" in  GitHub adds an  annotated tag  which is
#   treated  as a  branch.  The  Travis build  has the  tag as  branch aand  the
#   variable TRAVIS_TAG set.

# - Setting an annotated tag in Git CLI and pushing to master (or another branch) with
#   --follow-tags triggers the Travis build



after_success:
  - |   # deploy snapshot
    if [ "$TRAVIS_EVENT_TYPE" == push -a "$TRAVIS_BRANCH" == "devel" ] &&
       [[ $MY_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+-SNAPSHOT$ ]]; then
      echo "PUBLISH DEVEL"
    fi

  - |  # deploy release
    if [ "$TRAVIS_EVENT_TYPE" == push -a -n "$TRAVIS_TAG" ] &&
       [[ $MY_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "RELEASE"
    fi
